"""CLAUDE.md linter.

Validates feature CLAUDE.md files against the expected schema and checks
for staleness:
  - Required sections present?
  - Public API matches actual barrel exports?
  - Referenced files still exist?
  - Manual section markers intact?
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path

from scarlet.analyzer.metadata import extract_feature_metadata


class IssueLevel(StrEnum):
    """Severity of a lint issue."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


@dataclass(frozen=True)
class LintIssue:
    """A single lint finding."""

    level: IssueLevel
    code: str
    message: str
    feature: str | None = None
    file: str | None = None

    def to_dict(self) -> dict:
        return {
            "level": self.level.value,
            "code": self.code,
            "message": self.message,
            "feature": self.feature,
            "file": self.file,
        }


@dataclass(frozen=True)
class LintReport:
    """A complete lint report for a feature or project."""

    feature: str
    issues: list[LintIssue] = field(default_factory=list)

    @property
    def has_errors(self) -> bool:
        return any(i.level == IssueLevel.ERROR for i in self.issues)

    @property
    def error_count(self) -> int:
        return sum(1 for i in self.issues if i.level == IssueLevel.ERROR)

    @property
    def warning_count(self) -> int:
        return sum(1 for i in self.issues if i.level == IssueLevel.WARNING)

    def to_dict(self) -> dict:
        return {
            "feature": self.feature,
            "error_count": self.error_count,
            "warning_count": self.warning_count,
            "issues": [i.to_dict() for i in self.issues],
        }


# Required section markers (manual sections that must exist in every CLAUDE.md)
REQUIRED_MANUAL_SECTIONS = {"description", "vocabulary", "conventions", "gotchas"}

# Auto sections that must be regenerated by scarlet
REQUIRED_AUTO_SECTIONS = {"public_api", "key_files", "consumers", "see_also"}


def lint_feature_claude_md(feature_path: Path) -> LintReport:
    """Lint a single feature's CLAUDE.md file.

    Two modes:
      - Scarlet-generated: full schema check (manual markers, auto sections,
        public API freshness, file references)
      - Legacy (no <!-- BEGIN MANUAL: --> markers): file reference check only,
        since the file wasn't generated from Scarlet's template.

    Args:
        feature_path: Absolute path to the feature directory.

    Returns:
        LintReport with all issues found.
    """
    feature_path = feature_path.resolve()
    issues: list[LintIssue] = []

    claude_md_path = feature_path / "CLAUDE.md"
    if not claude_md_path.exists():
        issues.append(
            LintIssue(
                level=IssueLevel.WARNING,
                code="missing_claude_md",
                message=f"Feature '{feature_path.name}' has no CLAUDE.md.",
                feature=feature_path.name,
            )
        )
        return LintReport(feature=feature_path.name, issues=issues)

    content = claude_md_path.read_text(encoding="utf-8")

    is_scarlet_generated = "<!-- BEGIN MANUAL:" in content

    if is_scarlet_generated:
        # Full schema check on Scarlet-generated files
        issues.extend(_check_required_sections(content, feature_path.name, str(claude_md_path)))
        issues.extend(_check_public_api_freshness(content, feature_path))

    # File reference check applies to all files
    issues.extend(_check_referenced_files(content, feature_path))

    return LintReport(feature=feature_path.name, issues=issues)


def _check_required_sections(content: str, feature: str, file: str) -> list[LintIssue]:
    """Verify all required manual and auto sections are present."""
    issues: list[LintIssue] = []

    found_manual = set(
        re.findall(r"<!-- BEGIN MANUAL: ([a-z_]+) -->", content)
    )
    found_auto = set(
        re.findall(r"<!-- BEGIN AUTO: ([a-z_]+) -->", content)
    )

    for section in REQUIRED_MANUAL_SECTIONS:
        if section not in found_manual:
            issues.append(
                LintIssue(
                    level=IssueLevel.WARNING,
                    code="missing_manual_section",
                    message=f"Missing manual section: '{section}'.",
                    feature=feature,
                    file=file,
                )
            )

    for section in REQUIRED_AUTO_SECTIONS:
        if section not in found_auto:
            issues.append(
                LintIssue(
                    level=IssueLevel.WARNING,
                    code="missing_auto_section",
                    message=f"Missing auto section: '{section}'. Regenerate with `scarlet describe {feature}`.",
                    feature=feature,
                    file=file,
                )
            )

    return issues


def _check_public_api_freshness(content: str, feature_path: Path) -> list[LintIssue]:
    """Check that the documented Public API section matches actual exports.

    Only checks symbols inside the auto-generated <!-- BEGIN AUTO: public_api -->
    block. Symbols mentioned elsewhere in the document (vocabulary, gotchas,
    code examples) are intentionally not checked, since they may legitimately
    reference imports from other features or third-party libraries.
    """
    issues: list[LintIssue] = []

    # Extract just the auto public_api block
    block_match = re.search(
        r"<!-- BEGIN AUTO: public_api -->(.*?)<!-- END AUTO: public_api -->",
        content,
        re.DOTALL,
    )
    if not block_match:
        return issues

    block_text = block_match.group(1)

    # Extract documented symbols (capitalized or use-prefixed identifiers in backticks)
    documented = set(re.findall(r"`([A-Za-z_][A-Za-z0-9_]*)`", block_text))
    documented = {
        s for s in documented if s[0].isupper() or (s.startswith("use") and len(s) > 3 and s[3].isupper())
    }

    # Extract actual exports
    metadata = extract_feature_metadata(feature_path)
    actual = {e.name for e in metadata.exports}

    stale = documented - actual
    for symbol in sorted(stale):
        issues.append(
            LintIssue(
                level=IssueLevel.WARNING,
                code="stale_public_api",
                message=(
                    f"`{symbol}` is in the Public API section but no longer exported. "
                    f"Run `scarlet describe {feature_path.name}` to refresh."
                ),
                feature=feature_path.name,
                file=str(feature_path / "CLAUDE.md"),
            )
        )

    return issues


SOURCE_EXTENSIONS = {
    ".js", ".jsx", ".ts", ".tsx", ".mjs", ".py", ".md", ".mdc", ".css",
    ".scss", ".sass", ".json", ".yml", ".yaml", ".toml", ".sql", ".sh",
}

# Path prefixes that indicate the file is project-root-relative, not feature-relative
PROJECT_ROOT_PREFIXES = (
    "frontend/", "backend/", "src/", "app/", "shared/", "shared-docs/",
    "docs/", "store/", "features/", "components/", "pages/", "api/",
    ".claude/", ".cursor/", ".github/", "tests/", "test/",
)


def _check_referenced_files(content: str, feature_path: Path) -> list[LintIssue]:
    """Check that file paths mentioned in the CLAUDE.md still exist.

    Conservative checks to minimize false positives:
      - Only flag paths whose extension is a known source/doc extension
      - Skip paths that are clearly project-root-relative (start with
        `frontend/`, `backend/`, `.claude/`, etc.)
      - A reference is considered valid if either the exact relative path
        resolves OR a file with the same basename exists anywhere in the
        feature folder
    """
    issues: list[LintIssue] = []

    # Match backticked paths that look like file references
    file_pattern = re.compile(r"`([\w./-]+\.\w{2,5})`")

    # Build a set of all file basenames in the feature for fuzzy matching
    all_files = {f.name for f in feature_path.rglob("*") if f.is_file()}

    seen: set[str] = set()
    for match in file_pattern.finditer(content):
        path_str = match.group(1)
        if path_str in seen:
            continue
        seen.add(path_str)

        # Filter to known source/doc file extensions
        ext = "." + path_str.rsplit(".", 1)[-1].lower()
        if ext not in SOURCE_EXTENSIONS:
            continue

        # Skip paths that are clearly project-root-relative
        if path_str.startswith(PROJECT_ROOT_PREFIXES):
            continue

        # Try as a relative path under the feature root
        candidate = feature_path / path_str
        if candidate.exists():
            continue

        # Try matching by basename anywhere in the feature folder
        basename = path_str.split("/")[-1]
        if basename in all_files:
            continue

        issues.append(
            LintIssue(
                level=IssueLevel.INFO,
                code="broken_file_reference",
                message=f"Referenced file does not exist: `{path_str}`.",
                feature=feature_path.name,
                file=str(feature_path / "CLAUDE.md"),
            )
        )

    return issues
