"""CLAUDE.md linter.

Validates feature CLAUDE.md files against the expected schema and checks
for staleness:
  - Required sections present?
  - Public API matches actual barrel exports?
  - Referenced files still exist?
  - Manual section markers intact?
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path

from scarlet.analyzer.metadata import extract_feature_metadata


class IssueLevel(StrEnum):
    """Severity of a lint issue."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


@dataclass(frozen=True)
class LintIssue:
    """A single lint finding."""

    level: IssueLevel
    code: str
    message: str
    feature: str | None = None
    file: str | None = None

    def to_dict(self) -> dict:
        return {
            "level": self.level.value,
            "code": self.code,
            "message": self.message,
            "feature": self.feature,
            "file": self.file,
        }


@dataclass(frozen=True)
class LintReport:
    """A complete lint report for a feature or project."""

    feature: str
    issues: list[LintIssue] = field(default_factory=list)

    @property
    def has_errors(self) -> bool:
        return any(i.level == IssueLevel.ERROR for i in self.issues)

    @property
    def error_count(self) -> int:
        return sum(1 for i in self.issues if i.level == IssueLevel.ERROR)

    @property
    def warning_count(self) -> int:
        return sum(1 for i in self.issues if i.level == IssueLevel.WARNING)

    def to_dict(self) -> dict:
        return {
            "feature": self.feature,
            "error_count": self.error_count,
            "warning_count": self.warning_count,
            "issues": [i.to_dict() for i in self.issues],
        }


# Required section markers (manual sections that must exist in every CLAUDE.md)
REQUIRED_MANUAL_SECTIONS = {"description", "vocabulary", "conventions", "gotchas"}

# Auto sections that must be regenerated by scarlet
REQUIRED_AUTO_SECTIONS = {"public_api", "key_files", "consumers", "see_also"}


def lint_feature_claude_md(feature_path: Path) -> LintReport:
    """Lint a single feature's CLAUDE.md file.

    Args:
        feature_path: Absolute path to the feature directory.

    Returns:
        LintReport with all issues found.
    """
    feature_path = feature_path.resolve()
    issues: list[LintIssue] = []

    claude_md_path = feature_path / "CLAUDE.md"
    if not claude_md_path.exists():
        issues.append(
            LintIssue(
                level=IssueLevel.WARNING,
                code="missing_claude_md",
                message=f"Feature '{feature_path.name}' has no CLAUDE.md.",
                feature=feature_path.name,
            )
        )
        return LintReport(feature=feature_path.name, issues=issues)

    content = claude_md_path.read_text(encoding="utf-8")

    # Check required sections
    issues.extend(_check_required_sections(content, feature_path.name, str(claude_md_path)))

    # Check public API matches actual exports
    issues.extend(_check_public_api_freshness(content, feature_path))

    # Check referenced files still exist
    issues.extend(_check_referenced_files(content, feature_path))

    return LintReport(feature=feature_path.name, issues=issues)


def _check_required_sections(content: str, feature: str, file: str) -> list[LintIssue]:
    """Verify all required manual and auto sections are present."""
    issues: list[LintIssue] = []

    found_manual = set(
        re.findall(r"<!-- BEGIN MANUAL: ([a-z_]+) -->", content)
    )
    found_auto = set(
        re.findall(r"<!-- BEGIN AUTO: ([a-z_]+) -->", content)
    )

    for section in REQUIRED_MANUAL_SECTIONS:
        if section not in found_manual:
            issues.append(
                LintIssue(
                    level=IssueLevel.WARNING,
                    code="missing_manual_section",
                    message=f"Missing manual section: '{section}'.",
                    feature=feature,
                    file=file,
                )
            )

    for section in REQUIRED_AUTO_SECTIONS:
        if section not in found_auto:
            issues.append(
                LintIssue(
                    level=IssueLevel.WARNING,
                    code="missing_auto_section",
                    message=f"Missing auto section: '{section}'. Regenerate with `scarlet describe {feature}`.",
                    feature=feature,
                    file=file,
                )
            )

    return issues


def _check_public_api_freshness(content: str, feature_path: Path) -> list[LintIssue]:
    """Check that the documented Public API matches actual exports."""
    issues: list[LintIssue] = []

    # Extract documented symbols
    documented = set(re.findall(r"`([A-Za-z_][A-Za-z0-9_]*)`", content))

    # Extract actual exports
    metadata = extract_feature_metadata(feature_path)
    actual = {e.name for e in metadata.exports}

    # Symbols documented but no longer exported
    stale = documented & {s for s in documented if not s[0].islower() or s.startswith("use")} - actual
    # Filter to plausible symbol names (not random backticked words)
    stale = {s for s in stale if s[0].isupper() or s.startswith("use")}

    for symbol in stale:
        if symbol not in actual:
            issues.append(
                LintIssue(
                    level=IssueLevel.INFO,
                    code="stale_symbol_reference",
                    message=f"`{symbol}` is documented but no longer in the feature's exports.",
                    feature=feature_path.name,
                    file=str(feature_path / "CLAUDE.md"),
                )
            )

    return issues


def _check_referenced_files(content: str, feature_path: Path) -> list[LintIssue]:
    """Check that file paths mentioned in the CLAUDE.md still exist."""
    issues: list[LintIssue] = []

    # Match backticked paths that look like file references
    file_pattern = re.compile(r"`([\w./-]+\.\w{2,4})`")
    for match in file_pattern.finditer(content):
        path_str = match.group(1)
        # Resolve relative to the feature root
        candidate = feature_path / path_str
        if not candidate.exists():
            # Could also be relative to project root — ignore those
            if not path_str.startswith(("frontend/", "src/", "shared-docs/")):
                issues.append(
                    LintIssue(
                        level=IssueLevel.INFO,
                        code="broken_file_reference",
                        message=f"Referenced file does not exist: `{path_str}`.",
                        feature=feature_path.name,
                        file=str(feature_path / "CLAUDE.md"),
                    )
                )

    return issues
